export const TYPES = {
  LOAD_DATA_START: "LOAD_DATA_START",
  LOAD_DATA_COMPLETE: "LOAD_DATA_COMPLETE",
  LOAD_DATA_FAILED: "LOAD_DATA_FAILED",
  GET_LOCATION_START: "GET_LOCATION_START",
  GET_LOCATION_COMPLETE: "GET_LOCATION_COMPLETE",
};